services:
    hifikabin.hidenewestuser.listener:
        class: hifikabin\hidenewestuser\event\listener
        arguments:
            - '@template'
            - '@config'
        tags:
            - { name: event.listener }
